apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webdix
  template:
    metadata:
      labels:
        app: webdix
    spec:
      containers:
      - name: webdix
        image: docker.io/anapsix/webdis
        env: 
        - name: REDIS_HOST
          value: redis
          
